version: "3.9"

services:
  kc:
    env_file:
      - ./keycloak/postgres-keycloak.env
      - ./.env
  api:
    env_file:
      - ./keycloak/postgres-api.env
      - ./.env
  webui:
    env_file:
      - ./keycloak/postgres-ui.env
      - ./.env
#    profiles:
#      - "dontbuild"
